/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The response of a list operation.
 */
class ResponseWithContinuationCostInsight extends Array {
  /**
   * Create a ResponseWithContinuationCostInsight.
   * @member {string} [nextLink] Link for next set of results.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of ResponseWithContinuationCostInsight
   *
   * @returns {object} metadata of ResponseWithContinuationCostInsight
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ResponseWithContinuation_CostInsight_',
      type: {
        name: 'Composite',
        className: 'ResponseWithContinuationCostInsight',
        modelProperties: {
          value: {
            required: false,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CostInsightElementType',
                  type: {
                    name: 'Composite',
                    className: 'CostInsight'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ResponseWithContinuationCostInsight;
