/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The response model for the list activity operation.
 *
 */
class ActivityListResult {
  /**
   * Create a ActivityListResult.
   * @property {array} [value] Gets or sets a list of activities.
   * @property {string} [nextLink] Gets or sets the next link.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ActivityListResult
   *
   * @returns {object} metadata of ActivityListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ActivityListResult',
      type: {
        name: 'Composite',
        className: 'ActivityListResult',
        modelProperties: {
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ActivityElementType',
                  type: {
                    name: 'Composite',
                    className: 'Activity'
                  }
              }
            }
          },
          nextLink: {
            required: false,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ActivityListResult;
