/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { BaseResource, CloudError } from "ms-rest-azure";
import * as moment from "moment";

export {

  BaseResource,
  CloudError
};

/**
 * Definition of the activity parameter validation set.
 */
export interface ActivityParameterValidationSet {
  /**
   * Gets or sets the name of the activity parameter validation set member.
   */
  memberValue?: string;
}

/**
 * Definition of the activity parameter.
 */
export interface ActivityParameter {
  /**
   * Gets or sets the name of the activity parameter.
   */
  name?: string;
  /**
   * Gets or sets the type of the activity parameter.
   */
  type?: string;
  /**
   * Gets or sets a Boolean value that indicates true if the parameter is required. If the value is
   * false, the parameter is optional.
   */
  isMandatory?: boolean;
  /**
   * Gets or sets a Boolean value that indicates true if the parameter is dynamic.
   */
  isDynamic?: boolean;
  /**
   * Gets or sets the position of the activity parameter.
   */
  position?: number;
  /**
   * Gets or sets a Boolean value that indicates true if the parameter can take values from the
   * incoming pipeline objects. This setting is used if the cmdlet must access the complete input
   * object. false indicates that the parameter cannot take values from the complete input object.
   */
  valueFromPipeline?: boolean;
  /**
   * Gets or sets a Boolean value that indicates true if the parameter can be filled from a
   * property of the incoming pipeline object that has the same name as this parameter. false
   * indicates that the parameter cannot be filled from the incoming pipeline object property with
   * the same name.
   */
  valueFromPipelineByPropertyName?: boolean;
  /**
   * Gets or sets a Boolean value that indicates true if the cmdlet parameter accepts all the
   * remaining command-line arguments that are associated with this parameter in the form of an
   * array. false if the cmdlet parameter does not accept all the remaining argument values.
   */
  valueFromRemainingArguments?: boolean;
  /**
   * Gets or sets the description of the activity parameter.
   */
  description?: string;
  /**
   * Gets or sets the validation set of activity parameter.
   */
  validationSet?: ActivityParameterValidationSet[];
}

/**
 * Definition of the activity parameter set.
 */
export interface ActivityParameterSet {
  /**
   * Gets or sets the name of the activity parameter set.
   */
  name?: string;
  /**
   * Gets or sets the parameters of the activity parameter set.
   */
  parameters?: ActivityParameter[];
}

/**
 * Definition of the activity output type.
 */
export interface ActivityOutputType {
  /**
   * Gets or sets the name of the activity output type.
   */
  name?: string;
  /**
   * Gets or sets the type of the activity output type.
   */
  type?: string;
}

/**
 * Definition of the activity.
 */
export interface Activity {
  /**
   * Gets or sets the id of the resource.
   */
  id?: string;
  /**
   * Gets the name of the activity.
   */
  readonly name?: string;
  /**
   * Gets or sets the user name of the activity.
   */
  definition?: string;
  /**
   * Gets or sets the parameter sets of the activity.
   */
  parameterSets?: ActivityParameterSet[];
  /**
   * Gets or sets the output types of the activity.
   */
  outputTypes?: ActivityOutputType[];
  /**
   * Gets or sets the creation time.
   */
  creationTime?: Date;
  /**
   * Gets or sets the last modified time.
   */
  lastModifiedTime?: Date;
  /**
   * Gets or sets the description.
   */
  description?: string;
}

/**
 * The response model for the list activity operation.
 */
export interface ActivityListResult {
  /**
   * Gets or sets a list of activities.
   */
  value?: Activity[];
  /**
   * Gets or sets the next link.
   */
  nextLink?: string;
}

/**
 * Definition of the module error info type.
 */
export interface ModuleErrorInfo {
  /**
   * Gets or sets the error code.
   */
  code?: string;
  /**
   * Gets or sets the error message.
   */
  message?: string;
}

/**
 * Definition of the runbook property type.
 */
export interface ContentHash {
  /**
   * Gets or sets the content hash algorithm used to hash the content.
   */
  algorithm: string;
  /**
   * Gets or sets expected hash value of the content.
   */
  value: string;
}

/**
 * Definition of the content link.
 */
export interface ContentLink {
  /**
   * Gets or sets the uri of the runbook content.
   */
  uri?: string;
  /**
   * Gets or sets the hash.
   */
  contentHash?: ContentHash;
  /**
   * Gets or sets the version of the content.
   */
  version?: string;
}

/**
 * The core properties of ARM resources
 */
export interface Resource extends BaseResource {
  /**
   * Fully qualified resource Id for the resource
   */
  readonly id?: string;
  /**
   * The name of the resource
   */
  readonly name?: string;
  /**
   * The type of the resource.
   */
  readonly type?: string;
}

/**
 * The resource model definition for a ARM tracked top level resource
 */
export interface TrackedResource extends Resource {
  /**
   * Resource tags.
   */
  tags?: { [propertyName: string]: string };
  /**
   * The Azure Region where the resource lives
   */
  location?: string;
}

/**
 * Definition of the module type.
 */
export interface Module extends TrackedResource {
  /**
   * Gets or sets the isGlobal flag of the module.
   */
  isGlobal?: boolean;
  /**
   * Gets or sets the version of the module.
   */
  version?: string;
  /**
   * Gets or sets the size in bytes of the module.
   */
  sizeInBytes?: number;
  /**
   * Gets or sets the activity count of the module.
   */
  activityCount?: number;
  /**
   * Gets or sets the provisioning state of the module. Possible values include: 'Created',
   * 'Creating', 'StartingImportModuleRunbook', 'RunningImportModuleRunbook', 'ContentRetrieved',
   * 'ContentDownloaded', 'ContentValidated', 'ConnectionTypeImported', 'ContentStored',
   * 'ModuleDataStored', 'ActivitiesStored', 'ModuleImportRunbookComplete', 'Succeeded', 'Failed',
   * 'Cancelled', 'Updating'
   */
  provisioningState?: string;
  /**
   * Gets or sets the contentLink of the module.
   */
  contentLink?: ContentLink;
  /**
   * Gets or sets the error info of the module.
   */
  error?: ModuleErrorInfo;
  /**
   * Gets or sets the creation time.
   */
  creationTime?: Date;
  /**
   * Gets or sets the last modified time.
   */
  lastModifiedTime?: Date;
  /**
   * Gets or sets the description.
   */
  description?: string;
  /**
   * Gets or sets type of module, if its composite or not.
   */
  isComposite?: boolean;
  /**
   * Gets or sets the etag of the resource.
   */
  etag?: string;
}

/**
 * The parameters supplied to the create or update module operation.
 */
export interface PythonPackageCreateParameters {
  /**
   * Gets or sets the module content link.
   */
  contentLink: ContentLink;
  /**
   * Gets or sets the tags attached to the resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * The parameters supplied to the update module operation.
 */
export interface PythonPackageUpdateParameters {
  /**
   * Gets or sets the tags attached to the resource.
   */
  tags?: { [propertyName: string]: string };
}

/**
 * Information about a field of a type.
 */
export interface TypeField {
  /**
   * Gets or sets the name of the field.
   */
  name?: string;
  /**
   * Gets or sets the type of the field.
   */
  type?: string;
}

/**
 * The response model for the list fields operation.
 */
export interface TypeFieldListResult {
  /**
   * Gets or sets a list of fields.
   */
  value?: TypeField[];
}

/**
 * ARM proxy resource.
 */
export interface ProxyResource extends Resource {
}

/**
 * Error response of an operation failure
 */
export interface ErrorResponse {
  /**
   * Error code
   */
  code?: string;
  /**
   * Error message indicating why the operation failed.
   */
  message?: string;
}

/**
 * Definition of the job stream.
 */
export interface JobStream {
  /**
   * Gets or sets the id of the resource.
   */
  id?: string;
  /**
   * Gets or sets the id of the job stream.
   */
  jobStreamId?: string;
  /**
   * Gets or sets the creation time of the job.
   */
  time?: Date;
  /**
   * Gets or sets the stream type. Possible values include: 'Progress', 'Output', 'Warning',
   * 'Error', 'Debug', 'Verbose', 'Any'
   */
  streamType?: string;
  /**
   * Gets or sets the stream text.
   */
  streamText?: string;
  /**
   * Gets or sets the summary.
   */
  summary?: string;
  /**
   * Gets or sets the values of the job stream.
   */
  value?: { [propertyName: string]: any };
}

/**
 * Definition of the runbook parameter type.
 */
export interface RunbookParameter {
  /**
   * Gets or sets the type of the parameter.
   */
  type?: string;
  /**
   * Gets or sets a Boolean value to indicate whether the parameter is madatory or not.
   */
  isMandatory?: boolean;
  /**
   * Get or sets the position of the parameter.
   */
  position?: number;
  /**
   * Gets or sets the default value of parameter.
   */
  defaultValue?: string;
}

export interface RunbookDraft {
  /**
   * Gets or sets whether runbook is in edit mode.
  */
  inEdit?: boolean;
  /**
   * Gets or sets the draft runbook content link.
  */
  draftContentLink?: ContentLink;
  /**
   * Gets or sets the creation time of the runbook draft.
  */
  creationTime?: Date;
  /**
   * Gets or sets the last modified time of the runbook draft.
  */
  lastModifiedTime?: Date;
  /**
   * Gets or sets the runbook draft parameters.
  */
  parameters?: { [propertyName: string]: RunbookParameter };
  /**
   * Gets or sets the runbook output types.
  */
  outputTypes?: string[];
}

/**
 * Definition of the runbook type.
*/
export interface Runbook extends TrackedResource {
  /**
   * Gets or sets the type of the runbook. Possible values include: 'Script', 'Graph',
   * 'PowerShellWorkflow', 'PowerShell', 'GraphPowerShellWorkflow', 'GraphPowerShell'
  */
  runbookType?: string;
  /**
   * Gets or sets the published runbook content link.
  */
  publishContentLink?: ContentLink;
  /**
   * Gets or sets the state of the runbook. Possible values include: 'New', 'Edit', 'Published'
  */
  state?: string;
  /**
   * Gets or sets verbose log option.
  */
  logVerbose?: boolean;
  /**
   * Gets or sets progress log option.
  */
  logProgress?: boolean;
  /**
   * Gets or sets the option to log activity trace of the runbook.
  */
  logActivityTrace?: number;
  /**
   * Gets or sets the job count of the runbook.
  */
  jobCount?: number;
  /**
   * Gets or sets the runbook parameters.
  */
  parameters?: { [propertyName: string]: RunbookParameter };
  /**
   * Gets or sets the runbook output types.
  */
  outputTypes?: string[];
  /**
   * Gets or sets the draft runbook properties.
  */
  draft?: RunbookDraft;
  /**
   * Gets or sets the provisioning state of the runbook. Possible values include: 'Succeeded'
  */
  provisioningState?: string;
  /**
   * Gets or sets the last modified by.
  */
  lastModifiedBy?: string;
  /**
   * Gets or sets the creation time.
  */
  creationTime?: Date;
  /**
   * Gets or sets the last modified time.
  */
  lastModifiedTime?: Date;
  /**
   * Gets or sets the description.
  */
  description?: string;
  /**
   * Gets or sets the etag of the resource.
  */
  etag?: string;
}

/**
 * The parameters supplied to the create or update runbook operation.
*/
export interface RunbookCreateOrUpdateParameters {
  /**
   * Gets or sets verbose log option.
  */
  logVerbose?: boolean;
  /**
   * Gets or sets progress log option.
  */
  logProgress?: boolean;
  /**
   * Gets or sets the type of the runbook. Possible values include: 'Script', 'Graph',
   * 'PowerShellWorkflow', 'PowerShell', 'GraphPowerShellWorkflow', 'GraphPowerShell'
  */
  runbookType: string;
  /**
   * Gets or sets the draft runbook properties.
  */
  draft?: RunbookDraft;
  /**
   * Gets or sets the published runbook content link.
  */
  publishContentLink?: ContentLink;
  /**
   * Gets or sets the description of the runbook.
  */
  description?: string;
  /**
   * Gets or sets the activity-level tracing options of the runbook.
  */
  logActivityTrace?: number;
  /**
   * Gets or sets the name of the resource.
  */
  name?: string;
  /**
   * Gets or sets the location of the resource.
  */
  location?: string;
  /**
   * Gets or sets the tags attached to the resource.
  */
  tags?: { [propertyName: string]: string };
}

/**
 * The parameters supplied to the update runbook operation.
*/
export interface RunbookUpdateParameters {
  /**
   * Gets or sets the description of the runbook.
  */
  description?: string;
  /**
   * Gets or sets verbose log option.
  */
  logVerbose?: boolean;
  /**
   * Gets or sets progress log option.
  */
  logProgress?: boolean;
  /**
   * Gets or sets the activity-level tracing options of the runbook.
  */
  logActivityTrace?: number;
  /**
   * Gets or sets the name of the resource.
  */
  name?: string;
  /**
   * Gets or sets the location of the resource.
  */
  location?: string;
  /**
   * Gets or sets the tags attached to the resource.
  */
  tags?: { [propertyName: string]: string };
}

/**
 * The response model for the undoedit runbook operation.
*/
export interface RunbookDraftUndoEditResult {
  /**
   * Possible values include: 'Continue', 'SwitchingProtocols', 'OK', 'Created', 'Accepted',
   * 'NonAuthoritativeInformation', 'NoContent', 'ResetContent', 'PartialContent',
   * 'MultipleChoices', 'Ambiguous', 'MovedPermanently', 'Moved', 'Found', 'Redirect', 'SeeOther',
   * 'RedirectMethod', 'NotModified', 'UseProxy', 'Unused', 'TemporaryRedirect',
   * 'RedirectKeepVerb', 'BadRequest', 'Unauthorized', 'PaymentRequired', 'Forbidden', 'NotFound',
   * 'MethodNotAllowed', 'NotAcceptable', 'ProxyAuthenticationRequired', 'RequestTimeout',
   * 'Conflict', 'Gone', 'LengthRequired', 'PreconditionFailed', 'RequestEntityTooLarge',
   * 'RequestUriTooLong', 'UnsupportedMediaType', 'RequestedRangeNotSatisfiable',
   * 'ExpectationFailed', 'UpgradeRequired', 'InternalServerError', 'NotImplemented', 'BadGateway',
   * 'ServiceUnavailable', 'GatewayTimeout', 'HttpVersionNotSupported'
  */
  statusCode?: string;
  requestId?: string;
}

/**
 * The parameters supplied to the create test job operation.
*/
export interface TestJobCreateParameters {
  /**
   * Gets or sets the parameters of the test job.
  */
  parameters?: { [propertyName: string]: string };
  /**
   * Gets or sets the runOn which specifies the group name where the job is to be executed.
  */
  runOn?: string;
}

/**
 * Definition of the test job.
*/
export interface TestJob {
  /**
   * Gets or sets the creation time of the test job.
  */
  creationTime?: Date;
  /**
   * Gets or sets the status of the test job.
  */
  status?: string;
  /**
   * Gets or sets the status details of the test job.
  */
  statusDetails?: string;
  /**
   * Gets or sets the runOn which specifies the group name where the job is to be executed.
  */
  runOn?: string;
  /**
   * Gets or sets the start time of the test job.
  */
  startTime?: Date;
  /**
   * Gets or sets the end time of the test job.
  */
  endTime?: Date;
  /**
   * Gets or sets the exception of the test job.
  */
  exception?: string;
  /**
   * Gets or sets the last modified time of the test job.
  */
  lastModifiedTime?: Date;
  /**
   * Gets or sets the last status modified time of the test job.
  */
  lastStatusModifiedTime?: Date;
  /**
   * Gets or sets the parameters of the test job.
  */
  parameters?: { [propertyName: string]: string };
  /**
   * The activity-level tracing options of the runbook.
  */
  logActivityTrace?: number;
}

/**
 * The parameters supplied to the create or update dratft runbook properties.
*/
export interface RunbookCreateOrUpdateDraftProperties {
  /**
   * Gets or sets verbose log option.
  */
  logVerbose?: boolean;
  /**
   * Gets or sets progress log option.
  */
  logProgress?: boolean;
  /**
   * Gets or sets the type of the runbook. Possible values include: 'Script', 'Graph',
   * 'PowerShellWorkflow', 'PowerShell', 'GraphPowerShellWorkflow', 'GraphPowerShell'
  */
  runbookType: string;
  /**
   * Gets or sets the draft runbook properties.
  */
  draft: RunbookDraft;
  /**
   * Gets or sets the description of the runbook.
  */
  description?: string;
  /**
   * Gets or sets the activity-level tracing options of the runbook.
  */
  logActivityTrace?: number;
}

/**
 * The parameters supplied to the create or update runbook operation.
*/
export interface RunbookCreateOrUpdateDraftParameters {
  /**
   * Content of the Runbook.
  */
  runbookContent: string;
}

/**
 * The response model for the list module operation.
*/
export interface ModuleListResult extends Array<Module> {
  /**
   * Gets or sets the next link.
  */
  nextLink?: string;
}

/**
 * The response model for the list runbook operation.
*/
export interface RunbookListResult extends Array<Runbook> {
  /**
   * Gets or sets the next link.
  */
  nextLink?: string;
}

/**
 * The response model for the list job stream operation.
*/
export interface JobStreamListResult extends Array<JobStream> {
  /**
   * Gets or sets the next link.
  */
  nextLink?: string;
}
