/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

var msRestAzure = require('ms-rest-azure');

exports.BaseResource = msRestAzure.BaseResource;
exports.CloudError = msRestAzure.CloudError;
exports.ActivityParameterValidationSet = require('./activityParameterValidationSet');
exports.ActivityParameter = require('./activityParameter');
exports.ActivityParameterSet = require('./activityParameterSet');
exports.ActivityOutputType = require('./activityOutputType');
exports.Activity = require('./activity');
exports.ActivityListResult = require('./activityListResult');
exports.ModuleErrorInfo = require('./moduleErrorInfo');
exports.ContentHash = require('./contentHash');
exports.ContentLink = require('./contentLink');
exports.Resource = require('./resource');
exports.TrackedResource = require('./trackedResource');
exports.Module = require('./module');
exports.PythonPackageCreateParameters = require('./pythonPackageCreateParameters');
exports.PythonPackageUpdateParameters = require('./pythonPackageUpdateParameters');
exports.TypeField = require('./typeField');
exports.TypeFieldListResult = require('./typeFieldListResult');
exports.ProxyResource = require('./proxyResource');
exports.ErrorResponse = require('./errorResponse');
exports.JobStream = require('./jobStream');
exports.RunbookParameter = require('./runbookParameter');
exports.RunbookDraft = require('./runbookDraft');
exports.Runbook = require('./runbook');
exports.RunbookCreateOrUpdateParameters = require('./runbookCreateOrUpdateParameters');
exports.RunbookUpdateParameters = require('./runbookUpdateParameters');
exports.RunbookDraftUndoEditResult = require('./runbookDraftUndoEditResult');
exports.TestJobCreateParameters = require('./testJobCreateParameters');
exports.TestJob = require('./testJob');
exports.RunbookCreateOrUpdateDraftProperties = require('./runbookCreateOrUpdateDraftProperties');
exports.RunbookCreateOrUpdateDraftParameters = require('./runbookCreateOrUpdateDraftParameters');
exports.ModuleListResult = require('./moduleListResult');
exports.RunbookListResult = require('./runbookListResult');
exports.JobStreamListResult = require('./jobStreamListResult');
