/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The response model for the list fields operation.
 *
 */
class TypeFieldListResult {
  /**
   * Create a TypeFieldListResult.
   * @property {array} [value] Gets or sets a list of fields.
   */
  constructor() {
  }

  /**
   * Defines the metadata of TypeFieldListResult
   *
   * @returns {object} metadata of TypeFieldListResult
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'TypeFieldListResult',
      type: {
        name: 'Composite',
        className: 'TypeFieldListResult',
        modelProperties: {
          value: {
            required: false,
            serializedName: 'value',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'TypeFieldElementType',
                  type: {
                    name: 'Composite',
                    className: 'TypeField'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = TypeFieldListResult;
