/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

import { BaseResource, CloudError } from "ms-rest-azure";
import * as moment from "moment";

export {

  BaseResource,
  CloudError
};

/**
 * Role Definitions filter
 */
export interface RoleDefinitionFilter {
  /**
   * Returns role definition with the specific name.
   */
  roleName?: string;
}

/**
 * Role definition permissions.
 */
export interface Permission {
  /**
   * Allowed actions.
   */
  actions?: string[];
  /**
   * Denied actions.
   */
  notActions?: string[];
}

/**
 * Operation
 */
export interface ProviderOperation {
  /**
   * The operation name.
   */
  name?: string;
  /**
   * The operation display name.
   */
  displayName?: string;
  /**
   * The operation description.
   */
  description?: string;
  /**
   * The operation origin.
   */
  origin?: string;
  /**
   * The operation properties.
   */
  properties?: any;
}

/**
 * Resource Type
 */
export interface ResourceType {
  /**
   * The resource type name.
   */
  name?: string;
  /**
   * The resource type display name.
   */
  displayName?: string;
  /**
   * The resource type operations.
   */
  operations?: ProviderOperation[];
}

/**
 * Provider Operations metadata
 */
export interface ProviderOperationsMetadata {
  /**
   * The provider id.
   */
  id?: string;
  /**
   * The provider name.
   */
  name?: string;
  /**
   * The provider type.
   */
  type?: string;
  /**
   * The provider display name.
   */
  displayName?: string;
  /**
   * The provider resource types
   */
  resourceTypes?: ResourceType[];
  /**
   * The provider operations.
   */
  operations?: ProviderOperation[];
}

/**
 * Role definition.
 */
export interface RoleDefinition {
  /**
   * The role definition ID.
   */
  readonly id?: string;
  /**
   * The role definition name.
   */
  readonly name?: string;
  /**
   * The role definition type.
   */
  readonly type?: string;
  /**
   * The role name.
   */
  roleName?: string;
  /**
   * The role definition description.
   */
  description?: string;
  /**
   * The role type.
   */
  roleType?: string;
  /**
   * Role definition permissions.
   */
  permissions?: Permission[];
  /**
   * Role definition assignable scopes.
   */
  assignableScopes?: string[];
}

/**
 * Permissions information.
 */
export interface PermissionGetResult extends Array<Permission> {
  /**
   * The URL to use for getting the next set of results.
   */
  nextLink?: string;
}

/**
 * Provider operations metadata list
 */
export interface ProviderOperationsMetadataListResult extends Array<ProviderOperationsMetadata> {
  /**
   * The URL to use for getting the next set of results.
   */
  nextLink?: string;
}

/**
 * Role definition list operation result.
 */
export interface RoleDefinitionListResult extends Array<RoleDefinition> {
  /**
   * The URL to use for getting the next set of results.
   */
  nextLink?: string;
}
