/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The parameters used to create or update an access control list (ACL) entry.
 *
 */
class AclCreateOrUpdateParameters {
  /**
   * Create a AclCreateOrUpdateParameters.
   * @member {string} aceType the access control list (ACL) entry type. UserObj
   * and GroupObj denote the owning user and group, respectively. Possible
   * values include: 'UserObj', 'GroupObj', 'Other', 'User', 'Group'
   * @member {uuid} principalId the Azure AD object ID of the user or group
   * being specified in the access control list (ACL) entry.
   * @member {string} permission the permission type of the access control list
   * (ACL) entry. Possible values include: 'None', 'Use', 'Create', 'Drop',
   * 'Alter', 'Write', 'All'
   */
  constructor() {
  }

  /**
   * Defines the metadata of AclCreateOrUpdateParameters
   *
   * @returns {object} metadata of AclCreateOrUpdateParameters
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'AclCreateOrUpdateParameters',
      type: {
        name: 'Composite',
        className: 'AclCreateOrUpdateParameters',
        modelProperties: {
          aceType: {
            required: true,
            serializedName: 'aceType',
            type: {
              name: 'String'
            }
          },
          principalId: {
            required: true,
            serializedName: 'principalId',
            type: {
              name: 'String'
            }
          },
          permission: {
            required: true,
            serializedName: 'permission',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = AclCreateOrUpdateParameters;
