/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The parameters used to delete an access control list (ACL) entry.
 *
 */
class AclDeleteParameters {
  /**
   * Create a AclDeleteParameters.
   * @member {string} aceType the access control list (ACL) entry type. UserObj
   * and GroupObj denote the owning user and group, respectively. Possible
   * values include: 'UserObj', 'GroupObj', 'Other', 'User', 'Group'
   * @member {uuid} principalId the Azure AD object ID of the user or group
   * being specified in the access control list (ACL) entry.
   */
  constructor() {
  }

  /**
   * Defines the metadata of AclDeleteParameters
   *
   * @returns {object} metadata of AclDeleteParameters
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'AclDeleteParameters',
      type: {
        name: 'Composite',
        className: 'AclDeleteParameters',
        modelProperties: {
          aceType: {
            required: true,
            serializedName: 'aceType',
            type: {
              name: 'String'
            }
          },
          principalId: {
            required: true,
            serializedName: 'principalId',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = AclDeleteParameters;
