/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * A Data Lake Analytics catalog access control list (ACL).
 */
class AclList extends Array {
  /**
   * Create a AclList.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of AclList
   *
   * @returns {object} metadata of AclList
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'AclList',
      type: {
        name: 'Composite',
        className: 'AclList',
        modelProperties: {
          nextLink: {
            required: false,
            serializedName: 'nextLink',
            type: {
              name: 'String'
            }
          },
          value: {
            required: false,
            readOnly: true,
            serializedName: '',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'AclElementType',
                  type: {
                    name: 'Composite',
                    className: 'Acl'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = AclList;
