/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * The parameters used to submit a new Data Lake Analytics Scope job. (Only for
 * use internally with Scope job type.)
 *
 * @extends models['CreateJobParameters']
 */
class CreateScopeJobParameters extends models['CreateJobParameters'] {
  /**
   * Create a CreateScopeJobParameters.
   * @member {object} [tags] The key-value pairs used to add additional
   * metadata to the job information.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of CreateScopeJobParameters
   *
   * @returns {object} metadata of CreateScopeJobParameters
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CreateScopeJobParameters',
      type: {
        name: 'Composite',
        className: 'CreateScopeJobParameters',
        modelProperties: {
          type: {
            required: true,
            serializedName: 'type',
            type: {
              name: 'Enum',
              allowedValues: [ 'USql', 'Hive', 'Scope' ]
            }
          },
          properties: {
            required: true,
            serializedName: 'properties',
            type: {
              name: 'Composite',
              polymorphicDiscriminator: {
                serializedName: 'type',
                clientName: 'type'
              },
              uberParent: 'CreateJobProperties',
              className: 'CreateJobProperties'
            }
          },
          name: {
            required: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          degreeOfParallelism: {
            required: false,
            serializedName: 'degreeOfParallelism',
            defaultValue: 1,
            type: {
              name: 'Number'
            }
          },
          priority: {
            required: false,
            serializedName: 'priority',
            type: {
              name: 'Number'
            }
          },
          logFilePatterns: {
            required: false,
            serializedName: 'logFilePatterns',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          related: {
            required: false,
            serializedName: 'related',
            type: {
              name: 'Composite',
              className: 'JobRelationshipProperties'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = CreateScopeJobParameters;
