/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Scope job properties used when submitting Scope jobs. (Only for use
 * internally with Scope job type.)
 *
 * @extends models['CreateJobProperties']
 */
class CreateScopeJobProperties extends models['CreateJobProperties'] {
  /**
   * Create a CreateScopeJobProperties.
   * @member {array} [resources] The list of resources that are required by the
   * job.
   * @member {string} [notifier] The list of email addresses, separated by
   * semi-colons, to notify when the job reaches a terminal state.
   */
  constructor() {
    super();
  }

  /**
   * Defines the metadata of CreateScopeJobProperties
   *
   * @returns {object} metadata of CreateScopeJobProperties
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Scope',
      type: {
        name: 'Composite',
        polymorphicDiscriminator: {
          serializedName: 'type',
          clientName: 'type'
        },
        uberParent: 'CreateJobProperties',
        className: 'CreateScopeJobProperties',
        modelProperties: {
          runtimeVersion: {
            required: false,
            serializedName: 'runtimeVersion',
            type: {
              name: 'String'
            }
          },
          script: {
            required: true,
            serializedName: 'script',
            type: {
              name: 'String'
            }
          },
          type: {
            required: true,
            serializedName: 'type',
            isPolymorphicDiscriminator: true,
            type: {
              name: 'String'
            }
          },
          resources: {
            required: false,
            serializedName: 'resources',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ScopeJobResourceElementType',
                  type: {
                    name: 'Composite',
                    className: 'ScopeJobResource'
                  }
              }
            }
          },
          notifier: {
            required: false,
            serializedName: 'notifier',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = CreateScopeJobProperties;
