/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import { BaseResource } from 'ms-rest-azure';
import { CloudError } from 'ms-rest-azure';
import * as moment from 'moment';

export { BaseResource } from 'ms-rest-azure';
export { CloudError } from 'ms-rest-azure';


/**
 * @class
 * Initializes a new instance of the JobInnerError class.
 * @constructor
 * The Data Lake Analytics job error details.
 *
 * @member {string} [errorId] The specific identifier for the type of error
 * encountered in the job.
 * @member {string} [severity] The severity level of the failure. Possible
 * values include: 'Warning', 'Error', 'Info', 'SevereWarning', 'Deprecated',
 * 'UserWarning'
 * @member {string} [source] The ultimate source of the failure (usually either
 * SYSTEM or USER).
 * @member {string} [message] The user friendly error message for the failure.
 * @member {string} [description] The error message description.
 * @member {string} [details] The details of the error message.
 * @member {number} [diagnosticCode] The diagnostic error code.
 * @member {string} [component] The component that failed.
 * @member {string} [resolution] The recommended resolution for the failure, if
 * any.
 * @member {string} [helpLink] The link to MSDN or Azure help for this type of
 * error, if any.
 * @member {string} [internalDiagnostics] The internal diagnostic stack trace
 * if the user requesting the job error details has sufficient permissions it
 * will be retrieved, otherwise it will be empty.
 * @member {object} [innerError] The inner error of this specific job error
 * message, if any.
 */
export interface JobInnerError {
  readonly errorId?: string;
  readonly severity?: string;
  readonly source?: string;
  readonly message?: string;
  readonly description?: string;
  readonly details?: string;
  readonly diagnosticCode?: number;
  readonly component?: string;
  readonly resolution?: string;
  readonly helpLink?: string;
  readonly internalDiagnostics?: string;
  readonly innerError?: JobInnerError;
}

/**
 * @class
 * Initializes a new instance of the JobErrorDetails class.
 * @constructor
 * The Data Lake Analytics job error details.
 *
 * @member {string} [errorId] The specific identifier for the type of error
 * encountered in the job.
 * @member {string} [severity] The severity level of the failure. Possible
 * values include: 'Warning', 'Error', 'Info', 'SevereWarning', 'Deprecated',
 * 'UserWarning'
 * @member {string} [source] The ultimate source of the failure (usually either
 * SYSTEM or USER).
 * @member {string} [message] The user friendly error message for the failure.
 * @member {string} [description] The error message description.
 * @member {string} [details] The details of the error message.
 * @member {number} [lineNumber] The specific line number in the job where the
 * error occured.
 * @member {number} [startOffset] The start offset in the job where the error
 * was found
 * @member {number} [endOffset] The end offset in the job where the error was
 * found.
 * @member {string} [resolution] The recommended resolution for the failure, if
 * any.
 * @member {string} [filePath] The path to any supplemental error files, if
 * any.
 * @member {string} [helpLink] The link to MSDN or Azure help for this type of
 * error, if any.
 * @member {string} [internalDiagnostics] The internal diagnostic stack trace
 * if the user requesting the job error details has sufficient permissions it
 * will be retrieved, otherwise it will be empty.
 * @member {object} [innerError] The inner error of this specific job error
 * message, if any.
 * @member {string} [innerError.errorId] The specific identifier for the type
 * of error encountered in the job.
 * @member {string} [innerError.severity] The severity level of the failure.
 * Possible values include: 'Warning', 'Error', 'Info', 'SevereWarning',
 * 'Deprecated', 'UserWarning'
 * @member {string} [innerError.source] The ultimate source of the failure
 * (usually either SYSTEM or USER).
 * @member {string} [innerError.message] The user friendly error message for
 * the failure.
 * @member {string} [innerError.description] The error message description.
 * @member {string} [innerError.details] The details of the error message.
 * @member {number} [innerError.diagnosticCode] The diagnostic error code.
 * @member {string} [innerError.component] The component that failed.
 * @member {string} [innerError.resolution] The recommended resolution for the
 * failure, if any.
 * @member {string} [innerError.helpLink] The link to MSDN or Azure help for
 * this type of error, if any.
 * @member {string} [innerError.internalDiagnostics] The internal diagnostic
 * stack trace if the user requesting the job error details has sufficient
 * permissions it will be retrieved, otherwise it will be empty.
 * @member {object} [innerError.innerError] The inner error of this specific
 * job error message, if any.
 */
export interface JobErrorDetails {
  readonly errorId?: string;
  readonly severity?: string;
  readonly source?: string;
  readonly message?: string;
  readonly description?: string;
  readonly details?: string;
  readonly lineNumber?: number;
  readonly startOffset?: number;
  readonly endOffset?: number;
  readonly resolution?: string;
  readonly filePath?: string;
  readonly helpLink?: string;
  readonly internalDiagnostics?: string;
  readonly innerError?: JobInnerError;
}

/**
 * @class
 * Initializes a new instance of the JobStateAuditRecord class.
 * @constructor
 * The Data Lake Analytics job state audit records for tracking the lifecycle
 * of a job.
 *
 * @member {string} [newState] The new state the job is in.
 * @member {date} [timeStamp] The time stamp that the state change took place.
 * @member {string} [requestedByUser] The user who requests the change.
 * @member {string} [details] The details of the audit log.
 */
export interface JobStateAuditRecord {
  readonly newState?: string;
  readonly timeStamp?: Date;
  readonly requestedByUser?: string;
  readonly details?: string;
}

/**
 * @class
 * Initializes a new instance of the JobProperties class.
 * @constructor
 * The common Data Lake Analytics job properties.
 *
 * @member {string} [runtimeVersion] The runtime version of the Data Lake
 * Analytics engine to use for the specific type of job being run.
 * @member {string} script The script to run. Please note that the maximum
 * script size is 3 MB.
 * @member {string} type Polymorphic Discriminator
 */
export interface JobProperties {
  runtimeVersion?: string;
  script: string;
  type: string;
}

/**
 * @class
 * Initializes a new instance of the JobInformationBasic class.
 * @constructor
 * The common Data Lake Analytics job information properties.
 *
 * @member {uuid} [jobId] The job's unique identifier (a GUID).
 * @member {string} name The friendly name of the job.
 * @member {string} type The job type of the current job (Hive, USql, or Scope
 * (for internal use only)). Possible values include: 'USql', 'Hive', 'Scope'
 * @member {string} [submitter] The user or account that submitted the job.
 * @member {number} [degreeOfParallelism] The degree of parallelism used for
 * this job. This must be greater than 0, if set to less than 0 it will default
 * to 1. Default value: 1 .
 * @member {number} [priority] The priority value for the current job. Lower
 * numbers have a higher priority. By default, a job has a priority of 1000.
 * This must be greater than 0.
 * @member {date} [submitTime] The time the job was submitted to the service.
 * @member {date} [startTime] The start time of the job.
 * @member {date} [endTime] The completion time of the job.
 * @member {string} [state] The job state. When the job is in the Ended state,
 * refer to Result and ErrorMessage for details. Possible values include:
 * 'Accepted', 'Compiling', 'Ended', 'New', 'Queued', 'Running', 'Scheduling',
 * 'Starting', 'Paused', 'WaitingForCapacity'
 * @member {string} [result] The result of job execution or the current result
 * of the running job. Possible values include: 'None', 'Succeeded',
 * 'Cancelled', 'Failed'
 * @member {string} [logFolder] The log folder path to use in the following
 * format:
 * adl://<accountName>.azuredatalakestore.net/system/jobservice/jobs/Usql/2016/03/13/17/18/5fe51957-93bc-4de0-8ddc-c5a4753b068b/logs/.
 * @member {array} [logFilePatterns] The list of log file name patterns to find
 * in the logFolder. '*' is the only matching character allowed. Example
 * format: jobExecution*.log or *mylog*.txt
 * @member {object} [related] The recurring job relationship information
 * properties.
 * @member {uuid} [related.pipelineId] The job relationship pipeline identifier
 * (a GUID).
 * @member {string} [related.pipelineName] The friendly name of the job
 * relationship pipeline, which does not need to be unique.
 * @member {string} [related.pipelineUri] The pipeline uri, unique, links to
 * the originating service for this pipeline.
 * @member {uuid} [related.runId] The run identifier (a GUID), unique
 * identifier of the iteration of this pipeline.
 * @member {uuid} [related.recurrenceId] The recurrence identifier (a GUID),
 * unique per activity/script, regardless of iterations. This is something to
 * link different occurrences of the same job together.
 * @member {string} [related.recurrenceName] The recurrence name, user friendly
 * name for the correlation between jobs.
 * @member {object} [tags] The key-value pairs used to add additional metadata
 * to the job information. (Only for use internally with Scope job type.)
 */
export interface JobInformationBasic {
  readonly jobId?: string;
  name: string;
  type: string;
  readonly submitter?: string;
  degreeOfParallelism?: number;
  priority?: number;
  readonly submitTime?: Date;
  readonly startTime?: Date;
  readonly endTime?: Date;
  readonly state?: string;
  readonly result?: string;
  readonly logFolder?: string;
  logFilePatterns?: string[];
  related?: JobRelationshipProperties;
  tags?: { [propertyName: string]: string };
}

/**
 * @class
 * Initializes a new instance of the JobInformation class.
 * @constructor
 * The extended Data Lake Analytics job information properties returned when
 * retrieving a specific job.
 *
 * @member {array} [errorMessage] The error message details for the job, if the
 * job failed.
 * @member {array} [stateAuditRecords] The job state audit records, indicating
 * when various operations have been performed on this job.
 * @member {object} properties The job specific properties.
 * @member {string} [properties.runtimeVersion] The runtime version of the Data
 * Lake Analytics engine to use for the specific type of job being run.
 * @member {string} [properties.script] The script to run. Please note that the
 * maximum script size is 3 MB.
 * @member {string} [properties.type] Polymorphic Discriminator
 */
export interface JobInformation extends JobInformationBasic {
  readonly errorMessage?: JobErrorDetails[];
  readonly stateAuditRecords?: JobStateAuditRecord[];
  properties: JobProperties;
}

/**
 * @class
 * Initializes a new instance of the JobRelationshipProperties class.
 * @constructor
 * Job relationship information properties including pipeline information,
 * correlation information, etc.
 *
 * @member {uuid} [pipelineId] The job relationship pipeline identifier (a
 * GUID).
 * @member {string} [pipelineName] The friendly name of the job relationship
 * pipeline, which does not need to be unique.
 * @member {string} [pipelineUri] The pipeline uri, unique, links to the
 * originating service for this pipeline.
 * @member {uuid} [runId] The run identifier (a GUID), unique identifier of the
 * iteration of this pipeline.
 * @member {uuid} recurrenceId The recurrence identifier (a GUID), unique per
 * activity/script, regardless of iterations. This is something to link
 * different occurrences of the same job together.
 * @member {string} [recurrenceName] The recurrence name, user friendly name
 * for the correlation between jobs.
 */
export interface JobRelationshipProperties {
  pipelineId?: string;
  pipelineName?: string;
  pipelineUri?: string;
  runId?: string;
  recurrenceId: string;
  recurrenceName?: string;
}

/**
 * @class
 * Initializes a new instance of the JobResource class.
 * @constructor
 * The Data Lake Analytics job resources.
 *
 * @member {string} [name] The name of the resource.
 * @member {string} [resourcePath] The path to the resource.
 * @member {string} [type] The job resource type. Possible values include:
 * 'VertexResource', 'JobManagerResource', 'StatisticsResource',
 * 'VertexResourceInUserFolder', 'JobManagerResourceInUserFolder',
 * 'StatisticsResourceInUserFolder'
 */
export interface JobResource {
  name?: string;
  resourcePath?: string;
  type?: string;
}

/**
 * @class
 * Initializes a new instance of the JobStatisticsVertex class.
 * @constructor
 * The detailed information for a vertex.
 *
 * @member {string} [name] The name of the vertex.
 * @member {uuid} [vertexId] The id of the vertex.
 * @member {moment.duration} [executionTime] The amount of execution time of
 * the vertex.
 * @member {number} [dataRead] The amount of data read of the vertex, in bytes.
 * @member {number} [peakMemUsage] The amount of peak memory usage of the
 * vertex, in bytes.
 */
export interface JobStatisticsVertex {
  readonly name?: string;
  readonly vertexId?: string;
  readonly executionTime?: moment.Duration;
  readonly dataRead?: number;
  readonly peakMemUsage?: number;
}

/**
 * @class
 * Initializes a new instance of the ResourceUsageStatistics class.
 * @constructor
 * The statistics information for resource usage.
 *
 * @member {number} [average] The average value.
 * @member {number} [minimum] The minimum value.
 * @member {number} [maximum] The maximum value.
 */
export interface ResourceUsageStatistics {
  readonly average?: number;
  readonly minimum?: number;
  readonly maximum?: number;
}

/**
 * @class
 * Initializes a new instance of the JobStatisticsVertexStage class.
 * @constructor
 * The Data Lake Analytics job statistics vertex stage information.
 *
 * @member {number} [dataRead] The amount of data read, in bytes.
 * @member {number} [dataReadCrossPod] The amount of data read across multiple
 * pods, in bytes.
 * @member {number} [dataReadIntraPod] The amount of data read in one pod, in
 * bytes.
 * @member {number} [dataToRead] The amount of data remaining to be read, in
 * bytes.
 * @member {number} [dataWritten] The amount of data written, in bytes.
 * @member {number} [duplicateDiscardCount] The number of duplicates that were
 * discarded.
 * @member {number} [failedCount] The number of failures that occured in this
 * stage.
 * @member {number} [maxVertexDataRead] The maximum amount of data read in a
 * single vertex, in bytes.
 * @member {number} [minVertexDataRead] The minimum amount of data read in a
 * single vertex, in bytes.
 * @member {number} [readFailureCount] The number of read failures in this
 * stage.
 * @member {number} [revocationCount] The number of vertices that were revoked
 * during this stage.
 * @member {number} [runningCount] The number of currently running vertices in
 * this stage.
 * @member {number} [scheduledCount] The number of currently scheduled vertices
 * in this stage.
 * @member {string} [stageName] The name of this stage in job execution.
 * @member {number} [succeededCount] The number of vertices that succeeded in
 * this stage.
 * @member {number} [tempDataWritten] The amount of temporary data written, in
 * bytes.
 * @member {number} [totalCount] The total vertex count for this stage.
 * @member {moment.duration} [totalFailedTime] The amount of time that failed
 * vertices took up in this stage.
 * @member {number} [totalProgress] The current progress of this stage, as a
 * percentage.
 * @member {moment.duration} [totalSucceededTime] The amount of time all
 * successful vertices took in this stage.
 * @member {number} [totalPeakMemUsage] The sum of the peak memory usage of all
 * the vertices in the stage, in bytes.
 * @member {moment.duration} [totalExecutionTime] The sum of the total
 * execution time of all the vertices in the stage.
 * @member {object} [maxDataReadVertex] the vertex with the maximum amount of
 * data read.
 * @member {string} [maxDataReadVertex.name] The name of the vertex.
 * @member {uuid} [maxDataReadVertex.vertexId] The id of the vertex.
 * @member {moment.duration} [maxDataReadVertex.executionTime] The amount of
 * execution time of the vertex.
 * @member {number} [maxDataReadVertex.dataRead] The amount of data read of the
 * vertex, in bytes.
 * @member {number} [maxDataReadVertex.peakMemUsage] The amount of peak memory
 * usage of the vertex, in bytes.
 * @member {object} [maxExecutionTimeVertex] the vertex with the maximum
 * execution time.
 * @member {string} [maxExecutionTimeVertex.name] The name of the vertex.
 * @member {uuid} [maxExecutionTimeVertex.vertexId] The id of the vertex.
 * @member {moment.duration} [maxExecutionTimeVertex.executionTime] The amount
 * of execution time of the vertex.
 * @member {number} [maxExecutionTimeVertex.dataRead] The amount of data read
 * of the vertex, in bytes.
 * @member {number} [maxExecutionTimeVertex.peakMemUsage] The amount of peak
 * memory usage of the vertex, in bytes.
 * @member {object} [maxPeakMemUsageVertex] the vertex with the maximum peak
 * memory usage.
 * @member {string} [maxPeakMemUsageVertex.name] The name of the vertex.
 * @member {uuid} [maxPeakMemUsageVertex.vertexId] The id of the vertex.
 * @member {moment.duration} [maxPeakMemUsageVertex.executionTime] The amount
 * of execution time of the vertex.
 * @member {number} [maxPeakMemUsageVertex.dataRead] The amount of data read of
 * the vertex, in bytes.
 * @member {number} [maxPeakMemUsageVertex.peakMemUsage] The amount of peak
 * memory usage of the vertex, in bytes.
 * @member {number} [estimatedVertexCpuCoreCount] The estimated vertex CPU core
 * count.
 * @member {number} [estimatedVertexPeakCpuCoreCount] The estimated vertex peak
 * CPU core count.
 * @member {number} [estimatedVertexMemSize] The estimated vertex memory size,
 * in bytes.
 * @member {object} [allocatedContainerCpuCoreCount] The statistics information
 * for the allocated container CPU core count.
 * @member {number} [allocatedContainerCpuCoreCount.average] The average value.
 * @member {number} [allocatedContainerCpuCoreCount.minimum] The minimum value.
 * @member {number} [allocatedContainerCpuCoreCount.maximum] The maximum value.
 * @member {object} [allocatedContainerMemSize] The statistics information for
 * the allocated container memory size.
 * @member {number} [allocatedContainerMemSize.average] The average value.
 * @member {number} [allocatedContainerMemSize.minimum] The minimum value.
 * @member {number} [allocatedContainerMemSize.maximum] The maximum value.
 * @member {object} [usedVertexCpuCoreCount] The statistics information for the
 * used vertex CPU core count.
 * @member {number} [usedVertexCpuCoreCount.average] The average value.
 * @member {number} [usedVertexCpuCoreCount.minimum] The minimum value.
 * @member {number} [usedVertexCpuCoreCount.maximum] The maximum value.
 * @member {object} [usedVertexPeakMemSize] The statistics information for the
 * used vertex peak memory size.
 * @member {number} [usedVertexPeakMemSize.average] The average value.
 * @member {number} [usedVertexPeakMemSize.minimum] The minimum value.
 * @member {number} [usedVertexPeakMemSize.maximum] The maximum value.
 */
export interface JobStatisticsVertexStage {
  readonly dataRead?: number;
  readonly dataReadCrossPod?: number;
  readonly dataReadIntraPod?: number;
  readonly dataToRead?: number;
  readonly dataWritten?: number;
  readonly duplicateDiscardCount?: number;
  readonly failedCount?: number;
  readonly maxVertexDataRead?: number;
  readonly minVertexDataRead?: number;
  readonly readFailureCount?: number;
  readonly revocationCount?: number;
  readonly runningCount?: number;
  readonly scheduledCount?: number;
  readonly stageName?: string;
  readonly succeededCount?: number;
  readonly tempDataWritten?: number;
  readonly totalCount?: number;
  readonly totalFailedTime?: moment.Duration;
  readonly totalProgress?: number;
  readonly totalSucceededTime?: moment.Duration;
  readonly totalPeakMemUsage?: number;
  readonly totalExecutionTime?: moment.Duration;
  maxDataReadVertex?: JobStatisticsVertex;
  maxExecutionTimeVertex?: JobStatisticsVertex;
  maxPeakMemUsageVertex?: JobStatisticsVertex;
  readonly estimatedVertexCpuCoreCount?: number;
  readonly estimatedVertexPeakCpuCoreCount?: number;
  readonly estimatedVertexMemSize?: number;
  allocatedContainerCpuCoreCount?: ResourceUsageStatistics;
  allocatedContainerMemSize?: ResourceUsageStatistics;
  usedVertexCpuCoreCount?: ResourceUsageStatistics;
  usedVertexPeakMemSize?: ResourceUsageStatistics;
}

/**
 * @class
 * Initializes a new instance of the JobStatistics class.
 * @constructor
 * The Data Lake Analytics job execution statistics.
 *
 * @member {date} [lastUpdateTimeUtc] The last update time for the statistics.
 * @member {date} [finalizingTimeUtc] The job finalizing start time.
 * @member {array} [stages] The list of stages for the job.
 */
export interface JobStatistics {
  readonly lastUpdateTimeUtc?: Date;
  readonly finalizingTimeUtc?: Date;
  readonly stages?: JobStatisticsVertexStage[];
}

/**
 * @class
 * Initializes a new instance of the JobDataPath class.
 * @constructor
 * A Data Lake Analytics job data path item.
 *
 * @member {uuid} [jobId] The ID of the job this data is for.
 * @member {string} [command] The command that this job data relates to.
 * @member {array} [paths] The list of paths to all of the job data.
 */
export interface JobDataPath {
  readonly jobId?: string;
  readonly command?: string;
  readonly paths?: string[];
}

/**
 * @class
 * Initializes a new instance of the Diagnostics class.
 * @constructor
 * Error diagnostic information for failed jobs.
 *
 * @member {string} [message] The error message.
 * @member {string} [severity] The severity of the error. Possible values
 * include: 'Warning', 'Error', 'Info', 'SevereWarning', 'Deprecated',
 * 'UserWarning'
 * @member {number} [lineNumber] The line number the error occured on.
 * @member {number} [columnNumber] The column where the error occured.
 * @member {number} [start] The starting index of the error.
 * @member {number} [end] The ending index of the error.
 */
export interface Diagnostics {
  readonly message?: string;
  readonly severity?: string;
  readonly lineNumber?: number;
  readonly columnNumber?: number;
  readonly start?: number;
  readonly end?: number;
}

/**
 * @class
 * Initializes a new instance of the USqlJobProperties class.
 * @constructor
 * U-SQL job properties used when retrieving U-SQL jobs.
 *
 * @member {array} [resources] The list of resources that are required by the
 * job.
 * @member {object} [statistics] The job specific statistics.
 * @member {date} [statistics.lastUpdateTimeUtc] The last update time for the
 * statistics.
 * @member {date} [statistics.finalizingTimeUtc] The job finalizing start time.
 * @member {array} [statistics.stages] The list of stages for the job.
 * @member {object} [debugData] The job specific debug data locations.
 * @member {uuid} [debugData.jobId] The ID of the job this data is for.
 * @member {string} [debugData.command] The command that this job data relates
 * to.
 * @member {array} [debugData.paths] The list of paths to all of the job data.
 * @member {array} [diagnostics] The diagnostics for the job.
 * @member {string} [algebraFilePath] The algebra file path after the job has
 * completed.
 * @member {moment.duration} [totalCompilationTime] The total time this job
 * spent compiling. This value should not be set by the user and will be
 * ignored if it is.
 * @member {moment.duration} [totalQueuedTime] The total time this job spent
 * queued. This value should not be set by the user and will be ignored if it
 * is.
 * @member {moment.duration} [totalRunningTime] The total time this job spent
 * executing. This value should not be set by the user and will be ignored if
 * it is.
 * @member {moment.duration} [totalPausedTime] The total time this job spent
 * paused. This value should not be set by the user and will be ignored if it
 * is.
 * @member {string} [rootProcessNodeId] The ID used to identify the job manager
 * coordinating job execution. This value should not be set by the user and
 * will be ignored if it is.
 * @member {string} [yarnApplicationId] The ID used to identify the yarn
 * application executing the job. This value should not be set by the user and
 * will be ignored if it is.
 * @member {number} [yarnApplicationTimeStamp] The timestamp (in ticks) for the
 * yarn application executing the job. This value should not be set by the user
 * and will be ignored if it is.
 * @member {string} [compileMode] The specific compilation mode for the job
 * used during execution. If this is not specified during submission, the
 * server will determine the optimal compilation mode. Possible values include:
 * 'Semantic', 'Full', 'SingleBox'
 */
export interface USqlJobProperties extends JobProperties {
  readonly resources?: JobResource[];
  statistics?: JobStatistics;
  debugData?: JobDataPath;
  readonly diagnostics?: Diagnostics[];
  readonly algebraFilePath?: string;
  readonly totalCompilationTime?: moment.Duration;
  readonly totalQueuedTime?: moment.Duration;
  readonly totalRunningTime?: moment.Duration;
  readonly totalPausedTime?: moment.Duration;
  readonly rootProcessNodeId?: string;
  readonly yarnApplicationId?: string;
  readonly yarnApplicationTimeStamp?: number;
  readonly compileMode?: string;
}

/**
 * @class
 * Initializes a new instance of the HiveJobProperties class.
 * @constructor
 * Hive job properties used when retrieving Hive jobs.
 *
 * @member {string} [logsLocation] The Hive logs location.
 * @member {string} [outputLocation] The location of Hive job output files
 * (both execution output and results).
 * @member {number} [statementCount] The number of statements that will be run
 * based on the script.
 * @member {number} [executedStatementCount] The number of statements that have
 * been run based on the script.
 */
export interface HiveJobProperties extends JobProperties {
  readonly logsLocation?: string;
  readonly outputLocation?: string;
  readonly statementCount?: number;
  readonly executedStatementCount?: number;
}

/**
 * @class
 * Initializes a new instance of the ScopeJobResource class.
 * @constructor
 * The Scope job resources. (Only for use internally with Scope job type.)
 *
 * @member {string} [name] The name of the resource.
 * @member {string} [path] The path to the resource.
 */
export interface ScopeJobResource {
  name?: string;
  path?: string;
}

/**
 * @class
 * Initializes a new instance of the ScopeJobProperties class.
 * @constructor
 * Scope job properties used when submitting and retrieving Scope jobs. (Only
 * for use internally with Scope job type.)
 *
 * @member {array} [resources] The list of resources that are required by the
 * job.
 * @member {string} [userAlgebraPath] The algebra file path after the job has
 * completed.
 * @member {string} [notifier] The list of email addresses, separated by
 * semi-colons, to notify when the job reaches a terminal state.
 * @member {moment.duration} [totalCompilationTime] The total time this job
 * spent compiling. This value should not be set by the user and will be
 * ignored if it is.
 * @member {moment.duration} [totalQueuedTime] The total time this job spent
 * queued. This value should not be set by the user and will be ignored if it
 * is.
 * @member {moment.duration} [totalRunningTime] The total time this job spent
 * executing. This value should not be set by the user and will be ignored if
 * it is.
 * @member {moment.duration} [totalPausedTime] The total time this job spent
 * paused. This value should not be set by the user and will be ignored if it
 * is.
 * @member {string} [rootProcessNodeId] The ID used to identify the job manager
 * coordinating job execution. This value should not be set by the user and
 * will be ignored if it is.
 * @member {string} [yarnApplicationId] The ID used to identify the yarn
 * application executing the job. This value should not be set by the user and
 * will be ignored if it is.
 */
export interface ScopeJobProperties extends JobProperties {
  readonly resources?: ScopeJobResource[];
  readonly userAlgebraPath?: string;
  notifier?: string;
  readonly totalCompilationTime?: moment.Duration;
  readonly totalQueuedTime?: moment.Duration;
  readonly totalRunningTime?: moment.Duration;
  readonly totalPausedTime?: moment.Duration;
  readonly rootProcessNodeId?: string;
  readonly yarnApplicationId?: string;
}

/**
 * @class
 * Initializes a new instance of the JobPipelineRunInformation class.
 * @constructor
 * Run info for a specific job pipeline.
 *
 * @member {uuid} [runId] The run identifier of an instance of pipeline
 * executions (a GUID).
 * @member {date} [lastSubmitTime] The time this instance was last submitted.
 */
export interface JobPipelineRunInformation {
  readonly runId?: string;
  readonly lastSubmitTime?: Date;
}

/**
 * @class
 * Initializes a new instance of the JobPipelineInformation class.
 * @constructor
 * Job Pipeline Information, showing the relationship of jobs and recurrences
 * of those jobs in a pipeline.
 *
 * @member {uuid} [pipelineId] The job relationship pipeline identifier (a
 * GUID).
 * @member {string} [pipelineName] The friendly name of the job relationship
 * pipeline, which does not need to be unique.
 * @member {string} [pipelineUri] The pipeline uri, unique, links to the
 * originating service for this pipeline.
 * @member {number} [numJobsFailed] The number of jobs in this pipeline that
 * have failed.
 * @member {number} [numJobsCanceled] The number of jobs in this pipeline that
 * have been canceled.
 * @member {number} [numJobsSucceeded] The number of jobs in this pipeline that
 * have succeeded.
 * @member {number} [auHoursFailed] The number of job execution hours that
 * resulted in failed jobs.
 * @member {number} [auHoursCanceled] The number of job execution hours that
 * resulted in canceled jobs.
 * @member {number} [auHoursSucceeded] The number of job execution hours that
 * resulted in successful jobs.
 * @member {date} [lastSubmitTime] The last time a job in this pipeline was
 * submitted.
 * @member {array} [runs] The list of recurrence identifiers representing each
 * run of this pipeline.
 * @member {array} [recurrences] The list of recurrence identifiers
 * representing each run of this pipeline.
 */
export interface JobPipelineInformation {
  readonly pipelineId?: string;
  readonly pipelineName?: string;
  readonly pipelineUri?: string;
  readonly numJobsFailed?: number;
  readonly numJobsCanceled?: number;
  readonly numJobsSucceeded?: number;
  readonly auHoursFailed?: number;
  readonly auHoursCanceled?: number;
  readonly auHoursSucceeded?: number;
  readonly lastSubmitTime?: Date;
  readonly runs?: JobPipelineRunInformation[];
  readonly recurrences?: string[];
}

/**
 * @class
 * Initializes a new instance of the JobRecurrenceInformation class.
 * @constructor
 * Recurrence job information for a specific recurrence.
 *
 * @member {uuid} [recurrenceId] The recurrence identifier (a GUID), unique per
 * activity/script, regardless of iterations. This is something to link
 * different occurrences of the same job together.
 * @member {string} [recurrenceName] The recurrence name, user friendly name
 * for the correlation between jobs.
 * @member {number} [numJobsFailed] The number of jobs in this recurrence that
 * have failed.
 * @member {number} [numJobsCanceled] The number of jobs in this recurrence
 * that have been canceled.
 * @member {number} [numJobsSucceeded] The number of jobs in this recurrence
 * that have succeeded.
 * @member {number} [auHoursFailed] The number of job execution hours that
 * resulted in failed jobs.
 * @member {number} [auHoursCanceled] The number of job execution hours that
 * resulted in canceled jobs.
 * @member {number} [auHoursSucceeded] The number of job execution hours that
 * resulted in successful jobs.
 * @member {date} [lastSubmitTime] The last time a job in this recurrence was
 * submitted.
 */
export interface JobRecurrenceInformation {
  readonly recurrenceId?: string;
  readonly recurrenceName?: string;
  readonly numJobsFailed?: number;
  readonly numJobsCanceled?: number;
  readonly numJobsSucceeded?: number;
  readonly auHoursFailed?: number;
  readonly auHoursCanceled?: number;
  readonly auHoursSucceeded?: number;
  readonly lastSubmitTime?: Date;
}

/**
 * @class
 * Initializes a new instance of the CreateJobProperties class.
 * @constructor
 * The common Data Lake Analytics job properties for job submission.
 *
 * @member {string} [runtimeVersion] The runtime version of the Data Lake
 * Analytics engine to use for the specific type of job being run.
 * @member {string} script The script to run. Please note that the maximum
 * script size is 3 MB.
 * @member {string} type Polymorphic Discriminator
 */
export interface CreateJobProperties {
  runtimeVersion?: string;
  script: string;
  type: string;
}

/**
 * @class
 * Initializes a new instance of the BaseJobParameters class.
 * @constructor
 * Data Lake Analytics Job Parameters base class for build and submit.
 *
 * @member {string} type The job type of the current job (Hive, USql, or Scope
 * (for internal use only)). Possible values include: 'USql', 'Hive', 'Scope'
 * @member {object} properties The job specific properties.
 * @member {string} [properties.runtimeVersion] The runtime version of the Data
 * Lake Analytics engine to use for the specific type of job being run.
 * @member {string} [properties.script] The script to run. Please note that the
 * maximum script size is 3 MB.
 * @member {string} [properties.type] Polymorphic Discriminator
 */
export interface BaseJobParameters {
  type: string;
  properties: CreateJobProperties;
}

/**
 * @class
 * Initializes a new instance of the CreateJobParameters class.
 * @constructor
 * The parameters used to submit a new Data Lake Analytics job.
 *
 * @member {string} name The friendly name of the job to submit.
 * @member {number} [degreeOfParallelism] The degree of parallelism to use for
 * this job. This must be greater than 0, if set to less than 0 it will default
 * to 1. Default value: 1 .
 * @member {number} [priority] The priority value to use for the current job.
 * Lower numbers have a higher priority. By default, a job has a priority of
 * 1000. This must be greater than 0.
 * @member {array} [logFilePatterns] The list of log file name patterns to find
 * in the logFolder. '*' is the only matching character allowed. Example
 * format: jobExecution*.log or *mylog*.txt
 * @member {object} [related] The recurring job relationship information
 * properties.
 * @member {uuid} [related.pipelineId] The job relationship pipeline identifier
 * (a GUID).
 * @member {string} [related.pipelineName] The friendly name of the job
 * relationship pipeline, which does not need to be unique.
 * @member {string} [related.pipelineUri] The pipeline uri, unique, links to
 * the originating service for this pipeline.
 * @member {uuid} [related.runId] The run identifier (a GUID), unique
 * identifier of the iteration of this pipeline.
 * @member {uuid} [related.recurrenceId] The recurrence identifier (a GUID),
 * unique per activity/script, regardless of iterations. This is something to
 * link different occurrences of the same job together.
 * @member {string} [related.recurrenceName] The recurrence name, user friendly
 * name for the correlation between jobs.
 */
export interface CreateJobParameters extends BaseJobParameters {
  name: string;
  degreeOfParallelism?: number;
  priority?: number;
  logFilePatterns?: string[];
  related?: JobRelationshipProperties;
}

/**
 * @class
 * Initializes a new instance of the CreateScopeJobParameters class.
 * @constructor
 * The parameters used to submit a new Data Lake Analytics Scope job. (Only for
 * use internally with Scope job type.)
 *
 * @member {object} [tags] The key-value pairs used to add additional metadata
 * to the job information.
 */
export interface CreateScopeJobParameters extends CreateJobParameters {
  tags?: { [propertyName: string]: string };
}

/**
 * @class
 * Initializes a new instance of the CreateUSqlJobProperties class.
 * @constructor
 * U-SQL job properties used when submitting U-SQL jobs.
 *
 * @member {string} [compileMode] The specific compilation mode for the job
 * used during execution. If this is not specified during submission, the
 * server will determine the optimal compilation mode. Possible values include:
 * 'Semantic', 'Full', 'SingleBox'
 */
export interface CreateUSqlJobProperties extends CreateJobProperties {
  compileMode?: string;
}

/**
 * @class
 * Initializes a new instance of the CreateScopeJobProperties class.
 * @constructor
 * Scope job properties used when submitting Scope jobs. (Only for use
 * internally with Scope job type.)
 *
 * @member {array} [resources] The list of resources that are required by the
 * job.
 * @member {string} [notifier] The list of email addresses, separated by
 * semi-colons, to notify when the job reaches a terminal state.
 */
export interface CreateScopeJobProperties extends CreateJobProperties {
  resources?: ScopeJobResource[];
  notifier?: string;
}

/**
 * @class
 * Initializes a new instance of the BuildJobParameters class.
 * @constructor
 * The parameters used to build a new Data Lake Analytics job.
 *
 * @member {string} [name] The friendly name of the job to build.
 */
export interface BuildJobParameters extends BaseJobParameters {
  name?: string;
}

/**
 * @class
 * Initializes a new instance of the UpdateJobParameters class.
 * @constructor
 * The parameters that can be used to update existing Data Lake Analytics job
 * information properties. (Only for use internally with Scope job type.)
 *
 * @member {number} [degreeOfParallelism] The degree of parallelism used for
 * this job. This must be greater than 0, if set to less than 0 it will default
 * to 1.
 * @member {number} [priority] The priority value for the current job. Lower
 * numbers have a higher priority. By default, a job has a priority of 1000.
 * This must be greater than 0.
 * @member {object} [tags] The key-value pairs used to add additional metadata
 * to the job information.
 */
export interface UpdateJobParameters {
  degreeOfParallelism?: number;
  priority?: number;
  tags?: { [propertyName: string]: string };
}


/**
 * @class
 * Initializes a new instance of the JobInfoListResult class.
 * @constructor
 * List of JobInfo items.
 *
 * @member {string} [nextLink] The link (url) to the next page of results.
 */
export interface JobInfoListResult extends Array<JobInformationBasic> {
  readonly nextLink?: string;
}

/**
 * @class
 * Initializes a new instance of the JobPipelineInformationListResult class.
 * @constructor
 * List of job pipeline information items.
 *
 * @member {string} [nextLink] The link (url) to the next page of results.
 */
export interface JobPipelineInformationListResult extends Array<JobPipelineInformation> {
  readonly nextLink?: string;
}

/**
 * @class
 * Initializes a new instance of the JobRecurrenceInformationListResult class.
 * @constructor
 * List of job recurrence information items.
 *
 * @member {string} [nextLink] The link (url) to the next page of results.
 */
export interface JobRecurrenceInformationListResult extends Array<JobRecurrenceInformation> {
  readonly nextLink?: string;
}
