/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

var msRestAzure = require('ms-rest-azure');

exports.BaseResource = msRestAzure.BaseResource;
exports.CloudError = msRestAzure.CloudError;
exports.JobInnerError = require('./jobInnerError');
exports.JobErrorDetails = require('./jobErrorDetails');
exports.JobStateAuditRecord = require('./jobStateAuditRecord');
exports.JobProperties = require('./jobProperties');
exports.JobInformationBasic = require('./jobInformationBasic');
exports.JobInformation = require('./jobInformation');
exports.JobRelationshipProperties = require('./jobRelationshipProperties');
exports.JobResource = require('./jobResource');
exports.JobStatisticsVertex = require('./jobStatisticsVertex');
exports.ResourceUsageStatistics = require('./resourceUsageStatistics');
exports.JobStatisticsVertexStage = require('./jobStatisticsVertexStage');
exports.JobStatistics = require('./jobStatistics');
exports.JobDataPath = require('./jobDataPath');
exports.Diagnostics = require('./diagnostics');
exports.USqlJobProperties = require('./uSqlJobProperties');
exports.HiveJobProperties = require('./hiveJobProperties');
exports.ScopeJobResource = require('./scopeJobResource');
exports.ScopeJobProperties = require('./scopeJobProperties');
exports.JobPipelineRunInformation = require('./jobPipelineRunInformation');
exports.JobPipelineInformation = require('./jobPipelineInformation');
exports.JobRecurrenceInformation = require('./jobRecurrenceInformation');
exports.CreateJobProperties = require('./createJobProperties');
exports.BaseJobParameters = require('./baseJobParameters');
exports.CreateJobParameters = require('./createJobParameters');
exports.CreateScopeJobParameters = require('./createScopeJobParameters');
exports.CreateUSqlJobProperties = require('./createUSqlJobProperties');
exports.CreateScopeJobProperties = require('./createScopeJobProperties');
exports.BuildJobParameters = require('./buildJobParameters');
exports.UpdateJobParameters = require('./updateJobParameters');
exports.JobInfoListResult = require('./jobInfoListResult');
exports.JobPipelineInformationListResult = require('./jobPipelineInformationListResult');
exports.JobRecurrenceInformationListResult = require('./jobRecurrenceInformationListResult');
exports.discriminators = {
  'JobProperties' : exports.JobProperties,
  'JobProperties.USql' : exports.USqlJobProperties,
  'JobProperties.Hive' : exports.HiveJobProperties,
  'JobProperties.Scope' : exports.ScopeJobProperties,
  'CreateJobProperties' : exports.CreateJobProperties,
  'CreateJobProperties.USql' : exports.CreateUSqlJobProperties,
  'CreateJobProperties.Scope' : exports.CreateScopeJobProperties
};
