/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The Data Lake Analytics job error details.
 *
 */
class JobErrorDetails {
  /**
   * Create a JobErrorDetails.
   * @member {string} [errorId] The specific identifier for the type of error
   * encountered in the job.
   * @member {string} [severity] The severity level of the failure. Possible
   * values include: 'Warning', 'Error', 'Info', 'SevereWarning', 'Deprecated',
   * 'UserWarning'
   * @member {string} [source] The ultimate source of the failure (usually
   * either SYSTEM or USER).
   * @member {string} [message] The user friendly error message for the
   * failure.
   * @member {string} [description] The error message description.
   * @member {string} [details] The details of the error message.
   * @member {number} [lineNumber] The specific line number in the job where
   * the error occured.
   * @member {number} [startOffset] The start offset in the job where the error
   * was found
   * @member {number} [endOffset] The end offset in the job where the error was
   * found.
   * @member {string} [resolution] The recommended resolution for the failure,
   * if any.
   * @member {string} [filePath] The path to any supplemental error files, if
   * any.
   * @member {string} [helpLink] The link to MSDN or Azure help for this type
   * of error, if any.
   * @member {string} [internalDiagnostics] The internal diagnostic stack trace
   * if the user requesting the job error details has sufficient permissions it
   * will be retrieved, otherwise it will be empty.
   * @member {object} [innerError] The inner error of this specific job error
   * message, if any.
   * @member {string} [innerError.errorId] The specific identifier for the type
   * of error encountered in the job.
   * @member {string} [innerError.severity] The severity level of the failure.
   * Possible values include: 'Warning', 'Error', 'Info', 'SevereWarning',
   * 'Deprecated', 'UserWarning'
   * @member {string} [innerError.source] The ultimate source of the failure
   * (usually either SYSTEM or USER).
   * @member {string} [innerError.message] The user friendly error message for
   * the failure.
   * @member {string} [innerError.description] The error message description.
   * @member {string} [innerError.details] The details of the error message.
   * @member {number} [innerError.diagnosticCode] The diagnostic error code.
   * @member {string} [innerError.component] The component that failed.
   * @member {string} [innerError.resolution] The recommended resolution for
   * the failure, if any.
   * @member {string} [innerError.helpLink] The link to MSDN or Azure help for
   * this type of error, if any.
   * @member {string} [innerError.internalDiagnostics] The internal diagnostic
   * stack trace if the user requesting the job error details has sufficient
   * permissions it will be retrieved, otherwise it will be empty.
   * @member {object} [innerError.innerError] The inner error of this specific
   * job error message, if any.
   */
  constructor() {
  }

  /**
   * Defines the metadata of JobErrorDetails
   *
   * @returns {object} metadata of JobErrorDetails
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'JobErrorDetails',
      type: {
        name: 'Composite',
        className: 'JobErrorDetails',
        modelProperties: {
          errorId: {
            required: false,
            readOnly: true,
            serializedName: 'errorId',
            type: {
              name: 'String'
            }
          },
          severity: {
            required: false,
            readOnly: true,
            serializedName: 'severity',
            type: {
              name: 'Enum',
              allowedValues: [ 'Warning', 'Error', 'Info', 'SevereWarning', 'Deprecated', 'UserWarning' ]
            }
          },
          source: {
            required: false,
            readOnly: true,
            serializedName: 'source',
            type: {
              name: 'String'
            }
          },
          message: {
            required: false,
            readOnly: true,
            serializedName: 'message',
            type: {
              name: 'String'
            }
          },
          description: {
            required: false,
            readOnly: true,
            serializedName: 'description',
            type: {
              name: 'String'
            }
          },
          details: {
            required: false,
            readOnly: true,
            serializedName: 'details',
            type: {
              name: 'String'
            }
          },
          lineNumber: {
            required: false,
            readOnly: true,
            serializedName: 'lineNumber',
            type: {
              name: 'Number'
            }
          },
          startOffset: {
            required: false,
            readOnly: true,
            serializedName: 'startOffset',
            type: {
              name: 'Number'
            }
          },
          endOffset: {
            required: false,
            readOnly: true,
            serializedName: 'endOffset',
            type: {
              name: 'Number'
            }
          },
          resolution: {
            required: false,
            readOnly: true,
            serializedName: 'resolution',
            type: {
              name: 'String'
            }
          },
          filePath: {
            required: false,
            readOnly: true,
            serializedName: 'filePath',
            type: {
              name: 'String'
            }
          },
          helpLink: {
            required: false,
            readOnly: true,
            serializedName: 'helpLink',
            type: {
              name: 'String'
            }
          },
          internalDiagnostics: {
            required: false,
            readOnly: true,
            serializedName: 'internalDiagnostics',
            type: {
              name: 'String'
            }
          },
          innerError: {
            required: false,
            readOnly: true,
            serializedName: 'innerError',
            type: {
              name: 'Composite',
              className: 'JobInnerError'
            }
          }
        }
      }
    };
  }
}

module.exports = JobErrorDetails;
