/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The detailed information for a vertex.
 *
 */
class JobStatisticsVertex {
  /**
   * Create a JobStatisticsVertex.
   * @member {string} [name] The name of the vertex.
   * @member {uuid} [vertexId] The id of the vertex.
   * @member {moment.duration} [executionTime] The amount of execution time of
   * the vertex.
   * @member {number} [dataRead] The amount of data read of the vertex, in
   * bytes.
   * @member {number} [peakMemUsage] The amount of peak memory usage of the
   * vertex, in bytes.
   */
  constructor() {
  }

  /**
   * Defines the metadata of JobStatisticsVertex
   *
   * @returns {object} metadata of JobStatisticsVertex
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'JobStatisticsVertex',
      type: {
        name: 'Composite',
        className: 'JobStatisticsVertex',
        modelProperties: {
          name: {
            required: false,
            readOnly: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          vertexId: {
            required: false,
            readOnly: true,
            serializedName: 'vertexId',
            type: {
              name: 'String'
            }
          },
          executionTime: {
            required: false,
            readOnly: true,
            serializedName: 'executionTime',
            type: {
              name: 'TimeSpan'
            }
          },
          dataRead: {
            required: false,
            readOnly: true,
            serializedName: 'dataRead',
            type: {
              name: 'Number'
            }
          },
          peakMemUsage: {
            required: false,
            readOnly: true,
            serializedName: 'peakMemUsage',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = JobStatisticsVertex;
