/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The statistics information for resource usage.
 *
 */
class ResourceUsageStatistics {
  /**
   * Create a ResourceUsageStatistics.
   * @member {number} [average] The average value.
   * @member {number} [minimum] The minimum value.
   * @member {number} [maximum] The maximum value.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ResourceUsageStatistics
   *
   * @returns {object} metadata of ResourceUsageStatistics
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ResourceUsageStatistics',
      type: {
        name: 'Composite',
        className: 'ResourceUsageStatistics',
        modelProperties: {
          average: {
            required: false,
            readOnly: true,
            serializedName: 'average',
            type: {
              name: 'Number'
            }
          },
          minimum: {
            required: false,
            readOnly: true,
            serializedName: 'minimum',
            type: {
              name: 'Number'
            }
          },
          maximum: {
            required: false,
            readOnly: true,
            serializedName: 'maximum',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = ResourceUsageStatistics;
