/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The Scope job resources. (Only for use internally with Scope job type.)
 *
 */
class ScopeJobResource {
  /**
   * Create a ScopeJobResource.
   * @member {string} [name] The name of the resource.
   * @member {string} [path] The path to the resource.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ScopeJobResource
   *
   * @returns {object} metadata of ScopeJobResource
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ScopeJobResource',
      type: {
        name: 'Composite',
        className: 'ScopeJobResource',
        modelProperties: {
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          path: {
            required: false,
            serializedName: 'path',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ScopeJobResource;
