/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The parameters that can be used to update existing Data Lake Analytics job
 * information properties. (Only for use internally with Scope job type.)
 *
 */
class UpdateJobParameters {
  /**
   * Create a UpdateJobParameters.
   * @member {number} [degreeOfParallelism] The degree of parallelism used for
   * this job. This must be greater than 0, if set to less than 0 it will
   * default to 1.
   * @member {number} [priority] The priority value for the current job. Lower
   * numbers have a higher priority. By default, a job has a priority of 1000.
   * This must be greater than 0.
   * @member {object} [tags] The key-value pairs used to add additional
   * metadata to the job information.
   */
  constructor() {
  }

  /**
   * Defines the metadata of UpdateJobParameters
   *
   * @returns {object} metadata of UpdateJobParameters
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'UpdateJobParameters',
      type: {
        name: 'Composite',
        className: 'UpdateJobParameters',
        modelProperties: {
          degreeOfParallelism: {
            required: false,
            serializedName: 'degreeOfParallelism',
            type: {
              name: 'Number'
            }
          },
          priority: {
            required: false,
            serializedName: 'priority',
            type: {
              name: 'Number'
            }
          },
          tags: {
            required: false,
            serializedName: 'tags',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = UpdateJobParameters;
