/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * A Data Lake Analytics catalog U-SQL table fragment item.
 *
 */
class USqlTableFragment {
  /**
   * Create a USqlTableFragment.
   * @member {uuid} [parentId] the parent object Id of the table fragment. The
   * parent could be a table or table partition.
   * @member {uuid} [fragmentId] the version of the catalog item.
   * @member {number} [indexId] the ordinal of the index which contains the
   * table fragment.
   * @member {number} [size] the data size of the table fragment in bytes.
   * @member {number} [rowCount] the number of rows in the table fragment.
   * @member {date} [createDate] the creation time of the table fragment.
   */
  constructor() {
  }

  /**
   * Defines the metadata of USqlTableFragment
   *
   * @returns {object} metadata of USqlTableFragment
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'USqlTableFragment',
      type: {
        name: 'Composite',
        className: 'USqlTableFragment',
        modelProperties: {
          parentId: {
            required: false,
            serializedName: 'parentId',
            type: {
              name: 'String'
            }
          },
          fragmentId: {
            required: false,
            serializedName: 'fragmentId',
            type: {
              name: 'String'
            }
          },
          indexId: {
            required: false,
            serializedName: 'indexId',
            type: {
              name: 'Number'
            }
          },
          size: {
            required: false,
            serializedName: 'size',
            type: {
              name: 'Number'
            }
          },
          rowCount: {
            required: false,
            serializedName: 'rowCount',
            type: {
              name: 'Number'
            }
          },
          createDate: {
            required: false,
            serializedName: 'createDate',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = USqlTableFragment;
