/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The max per-database DTU capability.
 *
 */
class ElasticPoolPerDatabaseMaxDtuCapability {
  /**
   * Create a ElasticPoolPerDatabaseMaxDtuCapability.
   * @property {number} [limit] The maximum DTUs per database.
   * @property {array} [supportedPerDatabaseMinDtus] The list of supported min
   * database DTUs.
   * @property {string} [status] The status of the capability. Possible values
   * include: 'Visible', 'Available', 'Default', 'Disabled'
   * @property {string} [reason] The reason for the capability not being
   * available.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ElasticPoolPerDatabaseMaxDtuCapability
   *
   * @returns {object} metadata of ElasticPoolPerDatabaseMaxDtuCapability
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ElasticPoolPerDatabaseMaxDtuCapability',
      type: {
        name: 'Composite',
        className: 'ElasticPoolPerDatabaseMaxDtuCapability',
        modelProperties: {
          limit: {
            required: false,
            readOnly: true,
            serializedName: 'limit',
            type: {
              name: 'Number'
            }
          },
          supportedPerDatabaseMinDtus: {
            required: false,
            readOnly: true,
            serializedName: 'supportedPerDatabaseMinDtus',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ElasticPoolPerDatabaseMinDtuCapabilityElementType',
                  type: {
                    name: 'Composite',
                    className: 'ElasticPoolPerDatabaseMinDtuCapability'
                  }
              }
            }
          },
          status: {
            required: false,
            readOnly: true,
            serializedName: 'status',
            type: {
              name: 'Enum',
              allowedValues: [ 'Visible', 'Available', 'Default', 'Disabled' ]
            }
          },
          reason: {
            required: false,
            serializedName: 'reason',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ElasticPoolPerDatabaseMaxDtuCapability;
