/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The elastic pool edition capability.
 *
 */
class ElasticPoolEditionCapability {
  /**
   * Create a ElasticPoolEditionCapability.
   * @property {string} [name] The elastic pool edition name.
   * @property {array} [supportedElasticPoolDtus] The list of supported elastic
   * pool DTU levels for the edition.
   * @property {string} [status] The status of the capability. Possible values
   * include: 'Visible', 'Available', 'Default', 'Disabled'
   * @property {string} [reason] The reason for the capability not being
   * available.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ElasticPoolEditionCapability
   *
   * @returns {object} metadata of ElasticPoolEditionCapability
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ElasticPoolEditionCapability',
      type: {
        name: 'Composite',
        className: 'ElasticPoolEditionCapability',
        modelProperties: {
          name: {
            required: false,
            readOnly: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          supportedElasticPoolDtus: {
            required: false,
            readOnly: true,
            serializedName: 'supportedElasticPoolDtus',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'ElasticPoolDtuCapabilityElementType',
                  type: {
                    name: 'Composite',
                    className: 'ElasticPoolDtuCapability'
                  }
              }
            }
          },
          status: {
            required: false,
            readOnly: true,
            serializedName: 'status',
            type: {
              name: 'Enum',
              allowedValues: [ 'Visible', 'Available', 'Default', 'Disabled' ]
            }
          },
          reason: {
            required: false,
            serializedName: 'reason',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ElasticPoolEditionCapability;
