/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

/* jshint latedef:false */
/* jshint forin:false */
/* jshint noempty:false */

'use strict';

var msRestAzure = require('ms-rest-azure');

exports.BaseResource = msRestAzure.BaseResource;
exports.CloudError = msRestAzure.CloudError;
exports.MaxSizeCapability = require('./maxSizeCapability');
exports.PerformanceLevelCapability = require('./performanceLevelCapability');
exports.ServiceLevelObjectiveCapability = require('./serviceLevelObjectiveCapability');
exports.EditionCapability = require('./editionCapability');
exports.ElasticPoolPerDatabaseMinDtuCapability = require('./elasticPoolPerDatabaseMinDtuCapability');
exports.ElasticPoolPerDatabaseMaxDtuCapability = require('./elasticPoolPerDatabaseMaxDtuCapability');
exports.ElasticPoolDtuCapability = require('./elasticPoolDtuCapability');
exports.ElasticPoolEditionCapability = require('./elasticPoolEditionCapability');
exports.ServerVersionCapability = require('./serverVersionCapability');
exports.LocationCapabilities = require('./locationCapabilities');
exports.Resource = require('./resource');
exports.ProxyResource = require('./proxyResource');
exports.SubscriptionUsage = require('./subscriptionUsage');
exports.TrackedResource = require('./trackedResource');
exports.SubscriptionUsageListResult = require('./subscriptionUsageListResult');
