/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The service objectives capability.
 *
 */
class ServiceLevelObjectiveCapability {
  /**
   * Create a ServiceLevelObjectiveCapability.
   * @property {uuid} [id] The unique ID of the service objective.
   * @property {string} [name] The service objective name.
   * @property {array} [supportedMaxSizes] The list of supported maximum
   * database sizes for this service objective.
   * @property {object} [performanceLevel] The performance level of the service
   * objective capability.
   * @property {number} [performanceLevel.value] Performance level value.
   * @property {string} [performanceLevel.unit] Unit type used to measure
   * service objective performance level. Possible values include: 'DTU'
   * @property {object} [includedMaxSize] The included (free) max size for this
   * service level objective.
   * @property {number} [includedMaxSize.limit] The maximum size limit (see
   * 'unit' for the units).
   * @property {string} [includedMaxSize.unit] The units that the limit is
   * expressed in. Possible values include: 'Megabytes', 'Gigabytes',
   * 'Terabytes', 'Petabytes'
   * @property {string} [includedMaxSize.status] The status of the capability.
   * Possible values include: 'Visible', 'Available', 'Default', 'Disabled'
   * @property {string} [includedMaxSize.reason] The reason for the capability
   * not being available.
   * @property {string} [status] The status of the capability. Possible values
   * include: 'Visible', 'Available', 'Default', 'Disabled'
   * @property {string} [reason] The reason for the capability not being
   * available.
   */
  constructor() {
  }

  /**
   * Defines the metadata of ServiceLevelObjectiveCapability
   *
   * @returns {object} metadata of ServiceLevelObjectiveCapability
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'ServiceLevelObjectiveCapability',
      type: {
        name: 'Composite',
        className: 'ServiceLevelObjectiveCapability',
        modelProperties: {
          id: {
            required: false,
            readOnly: true,
            serializedName: 'id',
            type: {
              name: 'String'
            }
          },
          name: {
            required: false,
            readOnly: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          supportedMaxSizes: {
            required: false,
            readOnly: true,
            serializedName: 'supportedMaxSizes',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'MaxSizeCapabilityElementType',
                  type: {
                    name: 'Composite',
                    className: 'MaxSizeCapability'
                  }
              }
            }
          },
          performanceLevel: {
            required: false,
            readOnly: true,
            serializedName: 'performanceLevel',
            type: {
              name: 'Composite',
              className: 'PerformanceLevelCapability'
            }
          },
          includedMaxSize: {
            required: false,
            readOnly: true,
            serializedName: 'includedMaxSize',
            type: {
              name: 'Composite',
              className: 'MaxSizeCapability'
            }
          },
          status: {
            required: false,
            readOnly: true,
            serializedName: 'status',
            type: {
              name: 'Enum',
              allowedValues: [ 'Visible', 'Available', 'Default', 'Disabled' ]
            }
          },
          reason: {
            required: false,
            serializedName: 'reason',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = ServiceLevelObjectiveCapability;
